/**
 * Principal/Income Classification Rules
 *
 * Texas Property Code 116 (Uniform Principal and Income Act)
 *
 * PRINCIPAL = The trust corpus itself (assets, capital)
 * INCOME = Earnings generated by the principal
 */

import type { AllocationClass } from '@/lib/type-utils'

export type { AllocationClass }

// Income types from schema
export type IncomeType =
    | 'DIVIDEND'
    | 'INTEREST'
    | 'RENT'
    | 'ROYALTY'
    | 'CAPITAL_GAIN'
    | 'SALE_PROCEEDS'
    | 'DISTRIBUTION'
    | 'OTHER'

// Expense types from schema
export type ExpenseType =
    | 'TAX'
    | 'INSURANCE'
    | 'MAINTENANCE'
    | 'REPAIR'
    | 'PROFESSIONAL_FEE'
    | 'TRUSTEE_FEE'
    | 'FILING_FEE'
    | 'UTILITY'
    | 'OTHER'

/**
 * Classification rules based on Texas Property Code 116
 */
const INCOME_TYPE_RULES: Record<IncomeType, AllocationClass> = {
    // Regular earnings from assets → INCOME
    DIVIDEND: 'INCOME',
    INTEREST: 'INCOME',
    RENT: 'INCOME',
    ROYALTY: 'INCOME',

    // Capital transactions → PRINCIPAL
    CAPITAL_GAIN: 'PRINCIPAL',
    SALE_PROCEEDS: 'PRINCIPAL',
    DISTRIBUTION: 'PRINCIPAL', // From another entity (pass-through)

    // Unknown → default to PRINCIPAL (conservative)
    OTHER: 'PRINCIPAL',
}

const EXPENSE_TYPE_RULES: Record<ExpenseType, AllocationClass> = {
    // Ordinary expenses → charged to INCOME
    TAX: 'INCOME', // Property taxes, income taxes on income
    INSURANCE: 'INCOME', // Regular insurance premiums
    MAINTENANCE: 'INCOME', // Routine upkeep
    REPAIR: 'INCOME', // Repairs (not improvements)
    UTILITY: 'INCOME', // Utilities

    // Administrative expenses → typically INCOME
    // (Note: Texas 116.204 allows 50/50 split, but we simplify to income)
    PROFESSIONAL_FEE: 'INCOME',
    TRUSTEE_FEE: 'INCOME',
    FILING_FEE: 'INCOME',

    // Unknown → default to INCOME (most expenses are ordinary)
    OTHER: 'INCOME',
}

/**
 * Special rules that override the defaults
 */
const SPECIAL_RULES: Record<string, AllocationClass> = {
    // Capital improvements increase principal value
    CAPITAL_IMPROVEMENT: 'PRINCIPAL',

    // Insurance proceeds for destroyed assets replace principal
    INSURANCE_PROCEEDS: 'PRINCIPAL',

    // Eminent domain/condemnation proceeds
    CONDEMNATION_PROCEEDS: 'PRINCIPAL',

    // Stock splits do not create income
    STOCK_SPLIT: 'PRINCIPAL',

    // Return of capital is not income
    RETURN_OF_CAPITAL: 'PRINCIPAL',
}

/**
 * Classify a transaction as PRINCIPAL or INCOME
 *
 * @param incomeType - For income/receipt transactions
 * @param expenseType - For expense/disbursement transactions
 * @param category - Optional category for special rules
 * @returns The allocation class (PRINCIPAL or INCOME)
 */
export function classifyTransaction(
    incomeType?: IncomeType | null,
    expenseType?: ExpenseType | null,
    category?: string | null,
): AllocationClass {
    // Check special rules first (highest priority)
    if (category) {
        const specialRule = SPECIAL_RULES[category.toUpperCase()]
        if (specialRule) {
            return specialRule
        }
    }

    // Check income type
    if (incomeType && INCOME_TYPE_RULES[incomeType]) {
        return INCOME_TYPE_RULES[incomeType]
    }

    // Check expense type
    if (expenseType && EXPENSE_TYPE_RULES[expenseType]) {
        return EXPENSE_TYPE_RULES[expenseType]
    }

    // Default to PRINCIPAL if nothing matches (conservative approach)
    return 'PRINCIPAL'
}

/**
 * Determine if a transaction should be marked as principal
 * (Convenience wrapper returning boolean for database isPrincipal field)
 */
export function isPrincipalTransaction(
    incomeType?: IncomeType | null,
    expenseType?: ExpenseType | null,
    category?: string | null,
): boolean {
    return (
        classifyTransaction(incomeType, expenseType, category) === 'PRINCIPAL'
    )
}

/**
 * Get human-readable explanation for classification
 */
export function getClassificationReason(
    incomeType?: IncomeType | null,
    expenseType?: ExpenseType | null,
    category?: string | null,
): string {
    const classification = classifyTransaction(
        incomeType,
        expenseType,
        category,
    )

    if (category && SPECIAL_RULES[category.toUpperCase()]) {
        return `${category} is classified as ${classification} per Texas Property Code 116`
    }

    if (incomeType) {
        if (classification === 'INCOME') {
            return `${incomeType} is regular earnings from trust assets (Income)`
        } else {
            return `${incomeType} affects trust corpus/capital (Principal)`
        }
    }

    if (expenseType) {
        if (classification === 'INCOME') {
            return `${expenseType} is an ordinary expense charged to Income`
        } else {
            return `${expenseType} is a capital expense charged to Principal`
        }
    }

    return `Classified as ${classification} by default`
}

/**
 * Get all available income types with their classifications
 * (Useful for UI dropdowns with hints)
 */
export function getIncomeTypeOptions(): Array<{
    value: IncomeType
    label: string
    classification: AllocationClass
}> {
    return [
        { value: 'RENT', label: 'Rent', classification: 'INCOME' },
        { value: 'DIVIDEND', label: 'Dividend', classification: 'INCOME' },
        { value: 'INTEREST', label: 'Interest', classification: 'INCOME' },
        { value: 'ROYALTY', label: 'Royalty', classification: 'INCOME' },
        {
            value: 'CAPITAL_GAIN',
            label: 'Capital Gain',
            classification: 'PRINCIPAL',
        },
        {
            value: 'SALE_PROCEEDS',
            label: 'Sale Proceeds',
            classification: 'PRINCIPAL',
        },
        {
            value: 'DISTRIBUTION',
            label: 'Distribution (from entity)',
            classification: 'PRINCIPAL',
        },
        { value: 'OTHER', label: 'Other', classification: 'PRINCIPAL' },
    ]
}

/**
 * Get all available expense types with their classifications
 */
export function getExpenseTypeOptions(): Array<{
    value: ExpenseType
    label: string
    classification: AllocationClass
}> {
    return [
        { value: 'TAX', label: 'Taxes', classification: 'INCOME' },
        { value: 'INSURANCE', label: 'Insurance', classification: 'INCOME' },
        {
            value: 'MAINTENANCE',
            label: 'Maintenance',
            classification: 'INCOME',
        },
        { value: 'REPAIR', label: 'Repairs', classification: 'INCOME' },
        { value: 'UTILITY', label: 'Utilities', classification: 'INCOME' },
        {
            value: 'PROFESSIONAL_FEE',
            label: 'Professional Fees',
            classification: 'INCOME',
        },
        {
            value: 'TRUSTEE_FEE',
            label: 'Trustee Fee',
            classification: 'INCOME',
        },
        { value: 'FILING_FEE', label: 'Filing Fees', classification: 'INCOME' },
        { value: 'OTHER', label: 'Other', classification: 'INCOME' },
    ]
}
